# Generated by Django 5.2 on 2025-04-09 12:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_postgres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='geolocalisation',
        ),
        migrations.AddField(
            model_name='produit',
            name='localisation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
